---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if port 3389 is open
      ansible.builtin.wait_for:
        port: 3389
        delay: 10

    - name: Show testing instruction
      ansible.builtin.debug:
        msg: "Please connect to: {{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:3389"
